/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 16.0.6 -fPIC -O3) */

module AOI21x1(A0, A1, B, Y);
  input A0;
  wire A0;
  input A1;
  wire A1;
  input B;
  wire B;
  output Y;
  wire Y;
endmodule

module BUFx1(A, Y);
  input A;
  wire A;
  output Y;
  wire Y;
endmodule

module DECAPx2();
endmodule

module ENDCAP_L();
endmodule

module ENDCAP_R();
endmodule

module FILLx1();
endmodule

module FILLx2();
endmodule

module FILLx4();
endmodule

module FUSED_A(ai, bi, aj, bj, oh0, oh1, oh2);
  input ai;
  wire ai;
  input aj;
  wire aj;
  input bi;
  wire bi;
  input bj;
  wire bj;
  output oh0;
  wire oh0;
  output oh1;
  wire oh1;
  output oh2;
  wire oh2;
endmodule

module FUSED_E(ai, bi, aj, bj, oh0, oh1, oh2);
  input ai;
  wire ai;
  input aj;
  wire aj;
  input bi;
  wire bi;
  input bj;
  wire bj;
  output oh0;
  wire oh0;
  output oh1;
  wire oh1;
  output oh2;
  wire oh2;
endmodule

module FUSED_F(ai, bi, aj, bj, oh1, oh2);
  input ai;
  wire ai;
  input aj;
  wire aj;
  input bi;
  wire bi;
  input bj;
  wire bj;
  output oh1;
  wire oh1;
  output oh2;
  wire oh2;
endmodule

module FUSED_G(ai, bi, aj, bj, noh1, noh2);
  input ai;
  wire ai;
  input aj;
  wire aj;
  input bi;
  wire bi;
  input bj;
  wire bj;
  output noh1;
  wire noh1;
  output noh2;
  wire noh2;
endmodule

module INVx1(A, Y);
  input A;
  wire A;
  output Y;
  wire Y;
endmodule

module INVx2(A, Y);
  input A;
  wire A;
  output Y;
  wire Y;
endmodule

module INVx4(A, Y);
  input A;
  wire A;
  output Y;
  wire Y;
endmodule

module MUX21x1(D0, D1, S, Y);
  input D0;
  wire D0;
  input D1;
  wire D1;
  input S;
  wire S;
  output Y;
  wire Y;
endmodule

module NAND2x1(A, B, Y);
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
endmodule

module NOR2x1(A, B, Y);
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
endmodule

module OAI21x1(A0, A1, B, Y);
  input A0;
  wire A0;
  input A1;
  wire A1;
  input B;
  wire B;
  output Y;
  wire Y;
endmodule

module TAPx1();
endmodule

module TIE_HI(Y);
  output Y;
  wire Y;
endmodule

module TIE_LO(Y);
  output Y;
  wire Y;
endmodule

module XNOR2x1(A, B, Y);
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
endmodule

module XNOR2x2(A, B, Y);
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
endmodule

module XOR2x1(A, B, Y);
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
endmodule

module XOR2x2(A, B, Y);
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
endmodule
